In [1]:
# conditional statement

In [2]:
if True: # indentiation is always 4 space
    print('Data Science')

Data Science


In [3]:
if True: # indentiation is always 4 space
    print('Data Science')

print('hello word')

Data Science
hello word


In [4]:
if True: # indentiation is always 4 space
    print('Data Science')
else:
    print('hello word')

Data Science


In [166]:
if True:
    print('Data science')

Data science


In [168]:
if True:
    print('ds')

ds


In [170]:
if False:
    print('Data Science')

print('bye for now')

bye for now


In [172]:
if True:  # indentitation is always 4 space
    print('data science')

print('bye for now')

data science
bye for now


In [5]:
if False:
    print('data science')

print('bye for now')


bye for now


In [174]:
# To print only even number
x=4
r=x%2
if r==0:
    print('even number')

even number


In [176]:
x=5
r=x%2
if r==0:
    print('even number')

print('odd number')

odd number


In [180]:
x=6
r=x%2
if r==0:
    print('even number')
print('odd number')

even number
odd number


In [186]:
x=10
r=x%2
if r==0:
    print('even number')

if r==1:
    print('odd number')

even number


In [188]:
x=11
r=x%2
if r==0:
    print('even number')

if r==1:
    print('odd number')

odd number


In [6]:
if True:
    print('Data science')

print('bye for now')

Data science
bye for now


In [192]:
x=11
r=x%2
if r==0:
    print('even number')

if r==1:
    print('odd number')

odd number


In [194]:
x=23
r=x%2
if r==0:
    print('even number')

if r!=0:
    print('odd number')

odd number


In [196]:
x=20
r=x%2
if r==0:
    print('even number')

if r!=0:
    print('odd number')

even number


In [198]:
x=14
r=x%2
if r==0:
    print('even number')

else:
    print('odd number')

even number


In [200]:
x=19
r=x%2
if r==0:
    print('even number')

else:
    print('odd number')



odd number


In [7]:
if True:
    print('Data science')

else:
    print('bye for now')

Data science


In [8]:
# check the number is even number or odd number
x=4
r=x%2
if r==0:
    print('Even number')

Even number


In [9]:
x=5
r=x%2
if r==0:
    print('Even number')

In [10]:
x=5
r=x%2
if r==0:
    print('Even number')

if r==1:
    print('odd number')

odd number


In [11]:
x=6
r=x%2
if r==0:
    print('Even number')

if r==1:
    print('odd number')

Even number


In [12]:
x=7
r=x%2
if r==0:
    print('Even number')

else:
    print('odd number')

odd number


In [13]:
# nested if
x=3
r=x%2
if r==0:
    print('Even number')
    if x>5:
        print('greater number')

else:
    print('odd number')

odd number


In [14]:
# nested if
x=4
r=x%2
if r==0:
    print('Even number')
    if x>5:
        print('greater number')

else:
    print('odd number')

Even number


In [15]:
# nested if
x=4
r=x%2
if r==0:
    print('Even number')
    if x>5:
        print('greater number')
    else:
        print('lesser number')
     

else:
    print('odd number')

Even number
lesser number


In [16]:
# nested if
x=15
r=x%2
if r==0:
    print('Even number')
    if x>5:
        print('greater number')
    else:
        print('lesser number')
     

else:
    print('odd number')

odd number


In [17]:
# nested if
x=16
r=x%2
if r==0:
    print('Even number')
    if x>5:
        print('greater number')
    else:
        print('lesser number')
     

else:
    print('odd number')

Even number
greater number


In [202]:
x=3
r=x%2
if r==0:
    print('even number')
    if x>5:
        print('greater number')

else:
    print('odd number')

odd number


In [204]:
x=14
r=x%2
if r==0:
    print('even number')
    if x>5:
        print('greater number')

else:
    print('odd number')

even number
greater number


In [208]:
x=2
r=x%2
if r==0:
    print('even number')
    if x>5:
        print('greater number')

else:
    print('odd number')

even number


In [210]:
x=6
r=x%2
if r==0:
    print('even number')
    if x>5:
        print('greater number')
    else:
        print('less number')

else:
    print('odd number')

even number
greater number


In [220]:
x=10
r=x%2
if r==0:
    print('even number')
    if x>5:
        print('greater number')
    else:
        print('not greater')

else:
    print('odd number')

even number
greater number


In [226]:
x=3
r=x%2
if r==0:
    print('even number')
    if x>5:
        print('greater number')
    else:
        print('not greater number')
else:
    print('odd number')

odd number


In [18]:
x=3
if x==1:
    print('one')

if x==2:
    print('two')

if x==3:
    print('three')

if x==4:
    print('four')

three


In [19]:
x=3
if x==1:
    print('one')

elif x==2:
    print('two')

elif x==3:
    print('three')

elif x==4:
    print('four')

three


In [20]:
x=10
if x==1:
    print('one')

elif x==2:
    print('two')

elif x==3:
    print('three')

elif x==4:
    print('four')

else:
    print('number not found')
    

number not found


In [230]:
x=7
if(x==1):
    print('one')
elif(x==2):
    print('two')
elif(x==3):
    print('three')
elif(x==4):
    print('four')
else:
    print('wrong output')
    

wrong output


In [232]:
x=4
if(x==1):
    print('one')
elif(x==2):
    print('two')
elif(x==3):
    print('three')
elif(x==4):
    print('four')
else:
    print('wrong output')
    

four


In [234]:
x=10
if(x==1):
    print('one')
elif(x==2):
    print('two')
elif(x==3):
    print('three')
elif(x==4):
    print('four')
else:
    print('wrong output')

wrong output


In [240]:
# short hand if
a=30
b=20
if a>b:
    print('a is greater than b')

a is greater than b


 # Loop

In [22]:
i=1   # initializing
while i<=5:      # condition
    print('data science')
    i=i+1      # increment

data science
data science
data science
data science
data science


In [23]:
i=1
while i<=5:
    print('data science:',i)
    i=i+1

data science: 1
data science: 2
data science: 3
data science: 4
data science: 5


In [24]:
i=5
while i>=1:
    print('data science:',i)
    i=i-1

data science: 5
data science: 4
data science: 3
data science: 2
data science: 1


In [25]:
i=1
while i<=5:
    print('data science')
    j=1
    while j<=4:
        print('techology')
        j=j+1

    i=i+1
    print()

     


data science
techology
techology
techology
techology

data science
techology
techology
techology
techology

data science
techology
techology
techology
techology

data science
techology
techology
techology
techology

data science
techology
techology
techology
techology



In [26]:
i=1
while i<=5:
    print('data science',end=" ")
    j=1
    while j<=4:
        print('techology',end=" ")
        j=j+1

    i=i+1
    print()

data science techology techology techology techology 
data science techology techology techology techology 
data science techology techology techology techology 
data science techology techology techology techology 
data science techology techology techology techology 


In [27]:
i=1
while i<=2:
    j=0
    while j<=2:
        print(i*j,end=" ")
        j+=1
    print()
    i+=1

0 1 2 
0 2 4 


In [28]:
i=1
while i<=4:
    j=0
    while j<=3:
        print(i*j,end=" ")
        j+=1
    print()
    i+=1

0 1 2 3 
0 2 4 6 
0 3 6 9 
0 4 8 12 


# for loop

In [30]:
name='swati'
for i in name:
    print(i)

s
w
a
t
i


In [31]:
name=[1,3.5,'hello'] # i want print the value individualy
for i in name:
    print(i)

1
3.5
hello


In [32]:
for i in range(5):
    print(i)


0
1
2
3
4


In [33]:
for i in range(1,10,3):
    print(i)

1
4
7


In [34]:
for i in range(1,51):
    if i%5==0:
        print(i)

5
10
15
20
25
30
35
40
45
50


In [35]:
import keyword
keyword.kwlist

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

In [36]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [37]:
for i in range(1,11):
    if i==5:
        break
    print(i)

1
2
3
4


In [38]:
for i in range(1,11):
    if i==8:
        continue
    print(i)

1
2
3
4
5
6
7
9
10


In [39]:
for i in range(1,11):
    if i==6:
        break
    print('hello:',i)


hello: 1
hello: 2
hello: 3
hello: 4
hello: 5


In [40]:
for i in range(1,11):
    pass

In [41]:
for i in range(1,51):
    if i%3==0:
      print(i)
print('end')

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
end


In [42]:
for i in range(1,51):
    if i%3==0:
        continue
    print(i)

print('end')

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
37
38
40
41
43
44
46
47
49
50
end


In [43]:
for i in range(1,51):
    if i%3==0 or i%5==0:
        continue
    print(i)

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49


In [44]:
ava=5 # the machine has only 5 choclet
x=int(input('how many choclets you want:?'))
i=1
while i<=x:
    print('choclet')
    i+=1

how many choclets you want:? 6


choclet
choclet
choclet
choclet
choclet
choclet


In [45]:
ava=5 # the machine has only 5 choclet
x=int(input('how many choclets you want:?'))
i=1
while i<=x:
    print('choclet')
    i+=1

how many choclets you want:? 11


choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet
choclet


In [164]:
available_choclet=5 # the machine has only 5 choclet
x=int(input('how many choclets you want:?'))
i=1
while i<=x:
    if i>available_choclet: # we stop the executive not entire code, i want to come out of while loop
        break # break is statement| means jump out of the loop
    print('choclet')
    i+=1

print('bye for now')

how many choclets you want:? 10


choclet
choclet
choclet
choclet
choclet
bye for now


In [47]:
n=5
for i in range(2,n):
    if n%i==0:
        print("not prime")
        break
else:
    print("prime")

prime


In [242]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [244]:
for i in range(1,11):
    if i==6:
        break
    print(i)

1
2
3
4
5


In [248]:
for i in range(1,11):
    if i==4:
        break
    print(i)

1
2
3


In [250]:
for i in range(1,11):
    if i==3:
        continue
    print(i)

1
2
4
5
6
7
8
9
10


In [254]:
for i in range(1,11):
    if i==6:
        continue
    print('hello:',i)

hello: 1
hello: 2
hello: 3
hello: 4
hello: 5
hello: 7
hello: 8
hello: 9
hello: 10


In [256]:
for i in range(1,11):
    pass

In [258]:
for i in range(1,51):
    if i%3==0:
        print(i)

print('end')

3
6
9
12
15
18
21
24
27
30
33
36
39
42
45
48
end


In [260]:
for i in range(1,51):
    if i%3==0:
        continue
    print(i)
print('end')

1
2
4
5
7
8
10
11
13
14
16
17
19
20
22
23
25
26
28
29
31
32
34
35
37
38
40
41
43
44
46
47
49
50
end


In [262]:
for i in range(1,51):
    if i%3==0 or i%5==0:
        continue
    print(i)

print('end')

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
end


In [264]:
for i in range(1,50):
    if i%3==0 or i%5==0:
        continue
    print(i)
print('end')

1
2
4
7
8
11
13
14
16
17
19
22
23
26
28
29
31
32
34
37
38
41
43
44
46
47
49
end


In [266]:
for i in range(1,51):
    if i%2==0:
        continue
    print(i)
print('bye')

1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49
bye


In [272]:
for i in range(1,5):
    i=i+1
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [276]:
for i in range(1,5):
   if i<=5:
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [278]:
for j in range(4):
    print('#')

#
#
#
#


In [280]:
for j in range(4):
    print('# # # #')

# # # #
# # # #
# # # #
# # # #


In [282]:
for j in range(4):
    print('#',end=' ')

# # # # 

In [284]:
for j in range(4):
    print('#',end=' ')

for j in range(4):
    print('#',end=' ')

# # # # # # # # 

In [286]:
for j in range(4):
    print('#',end=' ')
print()

for j in range(4):
    print('#',end=' ')

# # # # 
# # # # 

In [288]:
for j in range(4):
    print('#',end=' ')
print()

for j in range(4):
    print('#',end=' ')
print()

for j in range(4):
    print('#',end=' ')
print()

for j in range(4):
    print('#',end=' ')

# # # # 
# # # # 
# # # # 
# # # # 

In [290]:
for i in range(4):
    for j in range(4):
        print('#',end=' ')
    print()

# # # # 
# # # # 
# # # # 
# # # # 


In [298]:
for i in range(4):
    for j in range(i+1):
        print(' # ',end=' ')
    print()

 #  
 #   #  
 #   #   #  
 #   #   #   #  


In [296]:
for i in range(1,5):
    print(' # '*i)

 # 
 #  # 
 #  #  # 
 #  #  #  # 


In [304]:
for i in range(1,5):
    for j in range(4):
        if i>j:
            print('#',end='')
        print()

#



#
#


#
#
#

#
#
#
#


In [308]:
for i in range(4):
    for j in range(i):
        print(' # ',end=' ')
    print()


 #  
 #   #  
 #   #   #  


In [310]:
for i in range(4):
    for j in range(i+1):
        print(' # ',end=' ')
    print()

 #  
 #   #  
 #   #   #  
 #   #   #   #  


In [312]:
for i in range(4):
    for j in range(4-i):
        print(' # ',end=' ')
    print()

 #   #   #   #  
 #   #   #  
 #   #  
 #  


In [314]:
for i in range(1,5):
    print(' # '*(5-i))

 #  #  #  # 
 #  #  # 
 #  # 
 # 


# for else

In [317]:
nums=[12,15,18,21,26]

for num in nums:
    if num%5==0:
        print(num)

15


In [319]:
nums=[12,14,18,21,25,30,35]
for num in nums:
    if num%5==0:
        print(num)

25
30
35


In [321]:
nums=[12,14,18,21,25,20]

for num in nums:
    if num%5==0:
        print(num)

25
20


In [323]:
nums=[12,14,18,21,20,25]
for num in nums:
    if num%5==0:
        print(num)
        break

20


In [325]:
nums=[10,14,18,21,5,10]

for num in nums:
    if num%5==0:
        print(num)
        break

10


In [345]:
nums=[7,14,18,21,23,27]

for num in nums:
    if num%5==0:
        print(num)
        break
else:
    print('Number is not found') # every iteration it checking condition

Number is not found


In [347]:
num=[7,14]
for num in nums:
    if num%5==0:
        print(num)
        break
else:
    print('number not found')

number not found


In [335]:
nums=[10,14,18,21,20,27]

for num in nums:
    if num%5==0:
        print(num)
        break
    else:
        print('not found')

10


In [337]:
nums=[10,14,18,21,27,30]

for num in nums:
    if num%5==0:
        print(num)
        break
    else:
        print('not found')

10


In [341]:
num=13
for i in range(2,num):
    if num%i==0:
        print('not prime number')
        break
else:
    print('prime number')

prime number


# Right Angle Triangle Pattern

In [49]:
for i in range(1,6):
    print(' * ' *i)

 * 
 *  * 
 *  *  * 
 *  *  *  * 
 *  *  *  *  * 


# Inverted Right Angle Triangle Pattern

In [51]:
for i in range(5,0,-1):
    print(' * '*i)

 *  *  *  *  * 
 *  *  *  * 
 *  *  * 
 *  * 
 * 


# Pyramid Pattern

In [53]:
for i in range(1,6):
    print(''*(5-i)+' * '*(2*i-1))

 * 
 *  *  * 
 *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  *  *  *  *  * 


# Inverted Pyramid Pattern

In [55]:
for i in range(5,0,-1):
    print(''*(5-i)+' * '*(2*i-1))

 *  *  *  *  *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  * 
 *  *  * 
 * 


# Diamond Pattern

In [57]:
for i in range(1,6):
    print(''*(5-i)+' * '*(2*i-1))

for i in range(4,0,-1):
    print(''*(5-i)+' * '*(2*i-1))

 * 
 *  *  * 
 *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  *  *  *  *  * 
 *  *  *  *  *  *  * 
 *  *  *  *  * 
 *  *  * 
 * 


# Hallow Square Pattern

In [59]:
for i in range(5):
    for j in range(5):
        if i==0 or i==4 or j==0 or j==4:
            print('*',end='')
        else:
            print(' ',end='')
    print()
      
         

*****
*   *
*   *
*   *
*****


# full Square Pattern

In [61]:
for i in range(5):
    print(' * '*5)

 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 
 *  *  *  *  * 


# Right Angle Triangle(number pattern)

In [63]:
for i in range(1,6):
    print(' '.join(str(x) for x in range(1,i+1)))

1
1 2
1 2 3
1 2 3 4
1 2 3 4 5


# Inverted Right Angle Triangle

In [65]:
for i in range(5,0,-1):
    print(' '.join(str(x)for x in range(1,i+1)))

1 2 3 4 5
1 2 3 4
1 2 3
1 2
1


# Floyd's triangle

In [67]:
num=1
for i in range(1,6):
    for j in range(1,i+1):
        print(num,end=' ')
        num+=1
    print()   

1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


# Hallow Right Angle Triangle

In [69]:
for i in range(1,6):
    for j in range(1,i+1):
        if j==1 or j==i or i==5:
            print('*',end=' ')
        else:
            print(' ',end=' ')
    print()
        

* 
* * 
*   * 
*     * 
* * * * * 


# Hallow Diamond Pattern

In [71]:
for i in range(1,6):
    for j in range(5-i):
        print(' ',end=' ')
    for j in range(2*i-1):
        if j==0 or j==2*i-2 or i==5:
            print('*',end=' ')
        else:
            print(' ',end=' ')

    print()
            

        * 
      *   * 
    *       * 
  *           * 
* * * * * * * * * 


# Hallow Diamond Pattern

In [73]:
n=5
for i in range(1,n+1):
    for j in range(n-i):
        print(' ',end=' ')
    for j in range(2*i-1):
        if j==0 or j==2*i-2:
            print(' * ',end=' ')
        else:
            print(' ',end=' ')
    print()

for i in range(n-1,0,-1):
    for j in range(n-i):
        print(' ', end=' ')
    for j in range(2*i-1):
        if j==0 or j==2*i-2:
            print(' * ',end=' ')
        else:
            print(' ',end=' ')

    print()       

         *  
       *     *  
     *         *  
   *             *  
 *                 *  
   *             *  
     *         *  
       *     *  
         *  


# Hallow Diamond (Number pattern) 

In [75]:
n=5
for i in range(1,n+1):
    for j in range(n-i):
        print(' ',end=' ')
    for j in range(2*i-1):
        if j==0 or j==2*i-2:
            print(i,end=' ')
        else:
            print(' ',end=' ')
    print()
for i in range(n-1,0,-1):
    for j in range(n-i):
        print(' ',end=' ') 
    for j in range(2*i-1):
        if j==0 or j==2*i-2:
            print(i,end=' ')
        else:
            print(' ',end=' ')
     
    print()

        1 
      2   2 
    3       3 
  4           4 
5               5 
  4           4 
    3       3 
      2   2 
        1 


In [76]:
n=5
for i in range(1,n+1):
    for j in range(n-i):
        print(' ',end=' ')
    for j in range(2*i-1):
        if j==0 or j==2*i-2:
            print(i,end=' ')
        else:
            print(' ',end=' ')
    print()

for i in range(n-1,0,-1):
    for j in range(n-i):
        print(' ', end=' ')
    for j in range(2*i-1):
        if j==0 or j==2*i-2:
            print(i,end=' ')
        else:
            print(' ',end=' ')

    print()       

        1 
      2   2 
    3       3 
  4           4 
5               5 
  4           4 
    3       3 
      2   2 
        1 


# Butterfly Pattern

In [78]:
n=5
for i in range(1,n+1):
    for j in range(1,i+1):
        print(j,end=' ')
    for j in range(2*(n-i)):
        print(' ',end=' ')
    for j in range(1,i+1):
        print(j,end=' ')
    print()

for i in range(n,0,-1):
    for j in range(1,i+1):
        print(j,end=' ')
    for j in range(2*(n-i)):
        print(' ',end=' ')
    for j in range(1,i+1):
        print(j,end=' ')
    print()    

1                 1 
1 2             1 2 
1 2 3         1 2 3 
1 2 3 4     1 2 3 4 
1 2 3 4 5 1 2 3 4 5 
1 2 3 4 5 1 2 3 4 5 
1 2 3 4     1 2 3 4 
1 2 3         1 2 3 
1 2             1 2 
1                 1 


In [79]:
n=5
for i in range(1,n+1):
    for j in range(i):
        print('*',end=' ')
    for j in range(2*(n-i)):
        print(' ',end=' ')
    for j in range(i):
        print('*',end=' ')
    print()

for i in range(n,0,-1):
    for j in range(i):
        print('*',end=' ')
    for j in range(2*(n-i)):
        print(' ',end=' ')
    for j in range(i):
        print('*',end=' ')
    print()    

*                 * 
* *             * * 
* * *         * * * 
* * * *     * * * * 
* * * * * * * * * * 
* * * * * * * * * * 
* * * *     * * * * 
* * *         * * * 
* *             * * 
*                 * 


# Hallow Number Pyramid

In [81]:
n=5
for i in range(1,n+1):
    for j in range(n-i):
        print(' ',end=' ')

    for j in range(1,2*i):
        if j==1 or j==2*i-1 or i ==n:
            print(i,end= ' ')
        else:
            print(' ',end=' ')

    print()
        

        1 
      2   2 
    3       3 
  4           4 
5 5 5 5 5 5 5 5 5 


# Full Star Pyramid

In [83]:
n=5

for i in range(1, n + 1):
    
    for j in range(n - i):
        print(' ',end=' ')

    for j in range(2 * i - 1):
        print('*',end=' ')

    print()

        * 
      * * * 
    * * * * * 
  * * * * * * * 
* * * * * * * * * 


# Inverted Full Star Pyramid

In [85]:
n=5
for i in range(n,0,-1):
    for j in range(n-i):
        print(' ',end=' ')
    for j in range(2*i-1):
        print('*',end=' ')

    print()

* * * * * * * * * 
  * * * * * * * 
    * * * * * 
      * * * 
        * 


# Left Aligned Pyramid Pattern

In [87]:
n=5
for i in range(1,n+1):

    for j in range(i):
        print('*',end=' ')

    print()



* 
* * 
* * * 
* * * * 
* * * * * 


In [88]:
n=5
for i in range(1,n+1):

    for j in range(1,i+1):
        print(j,end=' ')

    print()

1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


# Right Aligned Pyramid Pattern

In [90]:
n=5
for i in range(1,n+1):
    for j in range(n-i):
        print(' ',end=' ')

    for j in range(1,i+1):
        print(j,end=' ')

    print()

        1 
      1 2 
    1 2 3 
  1 2 3 4 
1 2 3 4 5 


In [91]:
n=5
for i in range(1,n+1):
    for j in range(n-i):
        print(' ',end=' ')

    for j in range(i):
        print('*',end=' ')

    print()

        * 
      * * 
    * * * 
  * * * * 
* * * * * 


# Array in python

In [354]:
from array import *
arr=array('i',[])

n=int(input('enter the length of the array'))

for i in range(5):
    x=int(input('enter the next value'))
    arr.append(x)
print(arr)

enter the length of the array 2
enter the next value 4
enter the next value 5
enter the next value 3
enter the next value 8
enter the next value 7


array('i', [4, 5, 3, 8, 7])


In [356]:
# way of creating array using numpy
from numpy import*
arr=array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [358]:
print(arr.dtype)

int32


In [360]:
arr=array([1,2,3,4,5.9])
print(arr)

[1.  2.  3.  4.  5.9]


In [362]:
print(arr.dtype)

float64


In [364]:
arr2=array([1,2,3,4,5.9],float)
arr2

array([1. , 2. , 3. , 4. , 5.9])

In [366]:
arr3=array([1,2,3,4,5.9],int)
arr3

array([1, 2, 3, 4, 5])

In [372]:
import numpy as np

In [376]:
arr4=np.linspace(0,16,10)
arr4

array([ 0.        ,  1.77777778,  3.55555556,  5.33333333,  7.11111111,
        8.88888889, 10.66666667, 12.44444444, 14.22222222, 16.        ])

In [378]:
arr5=np.arange(0,10,2)
arr5

array([0, 2, 4, 6, 8])

In [380]:
arr6=np.zeros(5)
arr6

array([0., 0., 0., 0., 0.])

In [382]:
arr7=np.ones(5)
arr7

array([1., 1., 1., 1., 1.])