In [1]:
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
type(my_list)

list

In [9]:
arr=np.array(my_list)

In [11]:
arr

array([0, 1, 2, 3, 4, 5])

In [13]:
type(arr)

numpy.ndarray

In [15]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(10,20,3)

array([10, 13, 16, 19])

In [21]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros(5,dtype=int) # 1d array

array([0, 0, 0, 0, 0])

In [25]:
np.zeros((2,2)) # 2d array

array([[0., 0.],
       [0., 0.]])

In [27]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [29]:
np.zeros((5,10),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [35]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [37]:
np.tows(3)

AttributeError: module 'numpy' has no attribute 'tows'

In [ ]:
rand(4)

In [40]:
np.random.rand(4)

array([0.35699597, 0.34442235, 0.0114458 , 0.71520069])

In [42]:
np.random.rand(4,4)

array([[0.15156514, 0.53914526, 0.27960947, 0.36803216],
       [0.53059903, 0.60488825, 0.51810184, 0.47838165],
       [0.84715735, 0.52607155, 0.91178608, 0.67195342],
       [0.63715734, 0.92255784, 0.48443896, 0.48545019]])

In [44]:
np.random.rand(2,2)

array([[0.13879571, 0.04217219],
       [0.07252242, 0.41421286]])

In [46]:
np.random.randint(3)

2

In [48]:
np.random.randint(10,15)

11

In [50]:
np.random.randint(1,5,3)

array([4, 1, 3])

In [52]:
np.random.randint(1,5,4)

array([3, 1, 1, 1])

In [54]:
np.random.randint(5,2,3)

ValueError: low >= high

In [56]:
np.random.randint(-5,2,3)

array([-5, -3, -3])

In [58]:
np.random.randint(10,40,(10,10))

array([[39, 14, 38, 17, 34, 17, 30, 30, 19, 18],
       [32, 17, 18, 28, 30, 15, 12, 15, 38, 39],
       [24, 27, 36, 37, 34, 30, 38, 11, 25, 13],
       [17, 18, 39, 39, 20, 18, 13, 16, 35, 21],
       [25, 26, 17, 34, 28, 20, 15, 19, 22, 12],
       [13, 11, 17, 33, 10, 23, 34, 28, 11, 35],
       [24, 14, 38, 17, 14, 25, 13, 34, 23, 23],
       [27, 37, 32, 10, 35, 34, 11, 18, 17, 30],
       [29, 11, 36, 10, 38, 26, 28, 35, 27, 18],
       [17, 26, 22, 29, 19, 34, 27, 38, 19, 36]])

In [60]:
ri=np.random.randint(10,40,(10,10))
ri

array([[11, 39, 23, 18, 16, 37, 31, 15, 32, 16],
       [15, 14, 17, 13, 29, 11, 16, 30, 10, 34],
       [22, 15, 28, 29, 32, 27, 33, 26, 37, 12],
       [36, 18, 19, 23, 38, 22, 36, 39, 34, 18],
       [12, 23, 32, 36, 36, 18, 12, 12, 15, 33],
       [15, 33, 31, 33, 11, 31, 15, 14, 17, 32],
       [36, 37, 12, 11, 23, 30, 37, 35, 36, 32],
       [33, 11, 14, 26, 22, 31, 15, 34, 30, 19],
       [39, 38, 12, 32, 28, 27, 24, 32, 22, 34],
       [20, 11, 36, 13, 11, 30, 10, 22, 31, 27]])

In [62]:
len(ri) # it will print by default 10 raws

10

In [64]:
ri=np.random.randint(10,40,(3,5))
ri

array([[26, 32, 38, 39, 36],
       [15, 24, 10, 13, 14],
       [15, 24, 16, 20, 14]])

In [66]:
len(ri)

3

In [68]:
ri.shape

(3, 5)

In [70]:
id(ri)

2445335577776

# Slicing in 

In [74]:
ri[:]

array([[26, 32, 38, 39, 36],
       [15, 24, 10, 13, 14],
       [15, 24, 16, 20, 14]])

In [76]:
ri[1]

array([15, 24, 10, 13, 14])

In [78]:
ri[0:3]

array([[26, 32, 38, 39, 36],
       [15, 24, 10, 13, 14],
       [15, 24, 16, 20, 14]])

In [80]:
ri_1=np.random.randint(10,40,(10,10))
ri_1

array([[14, 12, 20, 38, 39, 20, 32, 32, 11, 36],
       [18, 29, 33, 32, 37, 28, 26, 18, 23, 14],
       [29, 10, 10, 18, 12, 17, 39, 37, 36, 10],
       [39, 25, 14, 32, 37, 22, 29, 31, 28, 35],
       [15, 16, 11, 11, 13, 23, 38, 20, 22, 15],
       [18, 35, 21, 26, 21, 38, 39, 12, 36, 36],
       [21, 12, 33, 23, 36, 18, 17, 27, 22, 18],
       [14, 28, 11, 20, 22, 26, 32, 28, 11, 29],
       [20, 36, 13, 31, 16, 29, 16, 13, 24, 26],
       [36, 23, 25, 23, 38, 26, 36, 32, 39, 15]])

In [82]:
ri_1.shape

(10, 10)

In [84]:
ri_1=np.random.randint(10,40,(10,10))
print(ri_1)

[[36 32 22 15 37 11 30 31 17 20]
 [38 10 22 39 19 39 12 26 16 17]
 [30 29 25 18 34 35 23 14 20 13]
 [22 35 35 29 23 27 30 13 13 37]
 [13 39 19 31 16 10 34 39 15 12]
 [23 31 19 26 12 33 12 33 18 29]
 [26 11 16 16 32 27 16 21 31 31]
 [10 10 20 29 23 27 29 13 12 26]
 [10 18 17 21 16 17 19 19 31 38]
 [12 20 17 15 31 26 19 14 26 20]]


In [86]:
ri_1.shape

(10, 10)

In [88]:
ri_1

array([[36, 32, 22, 15, 37, 11, 30, 31, 17, 20],
       [38, 10, 22, 39, 19, 39, 12, 26, 16, 17],
       [30, 29, 25, 18, 34, 35, 23, 14, 20, 13],
       [22, 35, 35, 29, 23, 27, 30, 13, 13, 37],
       [13, 39, 19, 31, 16, 10, 34, 39, 15, 12],
       [23, 31, 19, 26, 12, 33, 12, 33, 18, 29],
       [26, 11, 16, 16, 32, 27, 16, 21, 31, 31],
       [10, 10, 20, 29, 23, 27, 29, 13, 12, 26],
       [10, 18, 17, 21, 16, 17, 19, 19, 31, 38],
       [12, 20, 17, 15, 31, 26, 19, 14, 26, 20]])

In [90]:
ri_1[:]

array([[36, 32, 22, 15, 37, 11, 30, 31, 17, 20],
       [38, 10, 22, 39, 19, 39, 12, 26, 16, 17],
       [30, 29, 25, 18, 34, 35, 23, 14, 20, 13],
       [22, 35, 35, 29, 23, 27, 30, 13, 13, 37],
       [13, 39, 19, 31, 16, 10, 34, 39, 15, 12],
       [23, 31, 19, 26, 12, 33, 12, 33, 18, 29],
       [26, 11, 16, 16, 32, 27, 16, 21, 31, 31],
       [10, 10, 20, 29, 23, 27, 29, 13, 12, 26],
       [10, 18, 17, 21, 16, 17, 19, 19, 31, 38],
       [12, 20, 17, 15, 31, 26, 19, 14, 26, 20]])

In [92]:
ri_1[3:8]

array([[22, 35, 35, 29, 23, 27, 30, 13, 13, 37],
       [13, 39, 19, 31, 16, 10, 34, 39, 15, 12],
       [23, 31, 19, 26, 12, 33, 12, 33, 18, 29],
       [26, 11, 16, 16, 32, 27, 16, 21, 31, 31],
       [10, 10, 20, 29, 23, 27, 29, 13, 12, 26]])

In [94]:
ri_1[3,8] # it gives to the third row 7th index

13

In [96]:
ri_1

array([[36, 32, 22, 15, 37, 11, 30, 31, 17, 20],
       [38, 10, 22, 39, 19, 39, 12, 26, 16, 17],
       [30, 29, 25, 18, 34, 35, 23, 14, 20, 13],
       [22, 35, 35, 29, 23, 27, 30, 13, 13, 37],
       [13, 39, 19, 31, 16, 10, 34, 39, 15, 12],
       [23, 31, 19, 26, 12, 33, 12, 33, 18, 29],
       [26, 11, 16, 16, 32, 27, 16, 21, 31, 31],
       [10, 10, 20, 29, 23, 27, 29, 13, 12, 26],
       [10, 18, 17, 21, 16, 17, 19, 19, 31, 38],
       [12, 20, 17, 15, 31, 26, 19, 14, 26, 20]])

In [98]:
ri_1[-5]

array([23, 31, 19, 26, 12, 33, 12, 33, 18, 29])

In [100]:
print(ri_1[-5,-3])

33


In [102]:
ri_1[::3]

array([[36, 32, 22, 15, 37, 11, 30, 31, 17, 20],
       [22, 35, 35, 29, 23, 27, 30, 13, 13, 37],
       [26, 11, 16, 16, 32, 27, 16, 21, 31, 31],
       [12, 20, 17, 15, 31, 26, 19, 14, 26, 20]])

In [104]:
ri_1[::-1]

array([[12, 20, 17, 15, 31, 26, 19, 14, 26, 20],
       [10, 18, 17, 21, 16, 17, 19, 19, 31, 38],
       [10, 10, 20, 29, 23, 27, 29, 13, 12, 26],
       [26, 11, 16, 16, 32, 27, 16, 21, 31, 31],
       [23, 31, 19, 26, 12, 33, 12, 33, 18, 29],
       [13, 39, 19, 31, 16, 10, 34, 39, 15, 12],
       [22, 35, 35, 29, 23, 27, 30, 13, 13, 37],
       [30, 29, 25, 18, 34, 35, 23, 14, 20, 13],
       [38, 10, 22, 39, 19, 39, 12, 26, 16, 17],
       [36, 32, 22, 15, 37, 11, 30, 31, 17, 20]])

In [106]:
ri_1[::-5]

array([[12, 20, 17, 15, 31, 26, 19, 14, 26, 20],
       [13, 39, 19, 31, 16, 10, 34, 39, 15, 12]])

In [108]:
ri_1[2]

array([30, 29, 25, 18, 34, 35, 23, 14, 20, 13])

In [110]:
ri_1

array([[36, 32, 22, 15, 37, 11, 30, 31, 17, 20],
       [38, 10, 22, 39, 19, 39, 12, 26, 16, 17],
       [30, 29, 25, 18, 34, 35, 23, 14, 20, 13],
       [22, 35, 35, 29, 23, 27, 30, 13, 13, 37],
       [13, 39, 19, 31, 16, 10, 34, 39, 15, 12],
       [23, 31, 19, 26, 12, 33, 12, 33, 18, 29],
       [26, 11, 16, 16, 32, 27, 16, 21, 31, 31],
       [10, 10, 20, 29, 23, 27, 29, 13, 12, 26],
       [10, 18, 17, 21, 16, 17, 19, 19, 31, 38],
       [12, 20, 17, 15, 31, 26, 19, 14, 26, 20]])

In [112]:
print(ri_1[2]) 
print(ri_1[:,2])

[30 29 25 18 34 35 23 14 20 13]
[22 22 25 35 19 19 16 20 17 17]


In [114]:
ri_1[:,8]

array([17, 16, 20, 13, 15, 18, 31, 12, 31, 26])

In [116]:
ri_1[:,-8]

array([22, 22, 25, 35, 19, 19, 16, 20, 17, 17])

In [118]:
ri_1

array([[36, 32, 22, 15, 37, 11, 30, 31, 17, 20],
       [38, 10, 22, 39, 19, 39, 12, 26, 16, 17],
       [30, 29, 25, 18, 34, 35, 23, 14, 20, 13],
       [22, 35, 35, 29, 23, 27, 30, 13, 13, 37],
       [13, 39, 19, 31, 16, 10, 34, 39, 15, 12],
       [23, 31, 19, 26, 12, 33, 12, 33, 18, 29],
       [26, 11, 16, 16, 32, 27, 16, 21, 31, 31],
       [10, 10, 20, 29, 23, 27, 29, 13, 12, 26],
       [10, 18, 17, 21, 16, 17, 19, 19, 31, 38],
       [12, 20, 17, 15, 31, 26, 19, 14, 26, 20]])

In [120]:
ri_1[2:6,5:8]

array([[35, 23, 14],
       [27, 30, 13],
       [10, 34, 39],
       [33, 12, 33]])

In [122]:
ri_1[0:3,0:3]

array([[36, 32, 22],
       [38, 10, 22],
       [30, 29, 25]])

In [124]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [126]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [128]:
np.arange(1,13).reshape(5,4)

ValueError: cannot reshape array of size 12 into shape (5,4)

In [130]:
np.arange(1,13).reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [132]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [134]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

# Numpy Masking or Filter

In [137]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [139]:
id(mat)

2445335587856

In [141]:
mat.shape

(10, 10)

In [143]:
mat=np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [145]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [147]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [149]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [151]:
mat[mat==50]

array([50])

In [153]:
mat[mat!=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [155]:
mat[mat>50]

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Array Creation Function

In [158]:
import numpy as np

In [160]:
# create an array from a list
a=np.array([1,2,3])
print('Array a:',a)

Array a: [1 2 3]


In [162]:
# create an array with evenly spaced values
b=np.arange(0,10,3) # values from 0 to 10 with step 2
print('Array b:',b)

Array b: [0 3 6 9]


In [164]:
# create an array filled with zeros
d=np.zeros([2,3]) # 2*3 array of zeros
print('Array d:\n',d)

Array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [166]:
# Create an array filled with ones
e=np.ones([3,2]) # 3*2 array of ones 
print('Array e:\n',e)

Array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [168]:
# Create an indentity matrix
f=np.eye(4) # 4*4 indentity matrix
print("Identity matrix f:\n",f)

Identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Array Manipulation fun

In [171]:
# Reshape an array
a1=np.array([1,2,3]) # Reshape to 1*3
reshaped=np.reshape(a1,(1,3))
print("Reshaped array:",reshaped)

Reshaped array: [[1 2 3]]


In [173]:
# Reshape an array
a1=np.array([1,2,3]) # Reshape to 1*3
reshaped=np.reshape(a1,(3,1))
print("Reshaped array:",reshaped)

Reshaped array: [[1]
 [2]
 [3]]


In [175]:
# Flatten an array
f1=np.array([[1,2],[3,4],[5,6],[7,8],[9,10]])
flattened=np.ravel(f1) # Flatten to 1D array
print("Flatened array:",flattened)

Flatened array: [ 1  2  3  4  5  6  7  8  9 10]


In [177]:
# Transposed an array
e1=np.array([[1,2],[3,4]])
transposed=np.transpose(e1) # Transpose the array
print("Transposed array:",transposed)

Transposed array: [[1 3]
 [2 4]]


In [179]:
# Stack of vertically
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.vstack([a2,b2]) # stack a and b vertically
print("Stacked array:\n", stacked)

Stacked array:
 [[1 2]
 [3 4]]


In [181]:
# Stack of Horizontal
a2=np.array([1,2])
b2=np.array([3,4])
stacked=np.hstack([a2,b2]) # stack a and b horizontal
print("Stacked array:\n", stacked)

Stacked array:
 [1 2 3 4]


In [183]:
# Mathematically Functions

In [185]:
g=np.array([1,2,3,4])
added=np.add(g,2) #add 2 to each element
print("Added 2 to g:",added)

Added 2 to g: [3 4 5 6]


In [187]:
# Square each element
squared=np.power(g,2) # square each element
print("Squared g:",squared)

Squared g: [ 1  4  9 16]


In [189]:
# Square root of each element
sqrt_val=np.sqrt(g) # square root of each element
print("Square root of g:",sqrt_val)

Square root of g: [1.         1.41421356 1.73205081 2.        ]


In [191]:
print(a)
print(g)

[1 2 3]
[1 2 3 4]


In [193]:
a3=np.array([1,2,3])
dot_product=np.dot(a,g) # Dot product of a & g
print("Dot product of a1 & a")

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [195]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [197]:
a3=np.array([1,2,3])
dot_product=np.dot(a1,a) # Dot product of a & g
print("Dot product of a1 & a:",dot_product)

Dot product of a1 & a: 14


# Statistical Functions

In [200]:
s=np.array([1,2,3,4])
mean=np.mean(s)
print("Mean of s:",mean)

Mean of s: 2.5


In [202]:
# Standard Deviation of an array
var=np.var(s)
print("Variance of s:",var)

Variance of s: 1.25


In [204]:
std_dev=np.std(s)
print("Standard deviation of s",std_dev)

Standard deviation of s 1.118033988749895


In [206]:
minimum=np.min(s)
print("Min of s:",minimum)

Min of s: 1


In [208]:
maximum=np.max(s)
print("Mix of s:",maximum)

Mix of s: 4


# Random Sampling Fun

In [211]:
# Generate random values between 0 and 1
random_vals=np.random.rand(3) # Array of 3 random values between 0 and 1
print("Random values:",random_vals)

Random values: [0.63416013 0.82911449 0.73085866]


In [213]:
# Set seed for reproducibility
np.random.seed(0)
random_vals=np.random.rand(3)
print("Random values:",random_vals)

Random values: [0.5488135  0.71518937 0.60276338]


In [215]:
# Generate random integers 
rand_ints=np.random.randint(0,10,size=5) # Random integer between 0 & 10
print("Random integer:",rand_ints)

Random integer: [3 7 9 3 5]


In [217]:
# Set seed for reproducibility
np.random.seed(0)
rand_ints=np.random.randint(0,10,size=5)
print("Random integer:",rand_ints)

Random integer: [5 0 3 3 7]


# Boolean & Logical Functions

In [220]:
# check if all element are True
logical_test=np.array([True,False,True])
all_true=np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [222]:
# check if all element are True
logical_test=np.array([False,False,False])
all_true=np.all(logical_test)
print("All elements True:",all_true)

All elements True: False


In [224]:
# check if any elements are True
any_true=np.any(logical_test)
print("Any elements True:",any_true)

Any elements True: False


# Set Operations

In [227]:
# Intersection of two arrays
set_a=np.array([1,2,3,4])
set_b=np.array([3,4,5,6])
intersection=np.intersect1d(set_a,set_b)
print("Intersection of a and b:",intersection)

Intersection of a and b: [3 4]


In [229]:
# Union of two arrays
union=np.union1d(set_a,set_b)
print("Union of a and b:",union)

Union of a and b: [1 2 3 4 5 6]


# Array Attribute Functions

In [232]:
# Array attributes
a=np.array([1,2,3])
shape=a.shape  # shape of the array
size=a.size   # Number of elements
dimensions=a.ndim # Number of dimensions
dtype=a.dtype   # Data type of the array

print("Shape of a:",shape)
print("Size of a:",size)
print("Number of dimension of a:",dimensions)
print("Data type of a:",dtype)

Shape of a: (3,)
Size of a: 3
Number of dimension of a: 1
Data type of a: int32


# Other Functions 

In [235]:
# Create a copy of an array
a=np.array([1,2,3])
copied_array=np.copy(a) # create a copy of array a
print("Copied array:", copied_array)

Copied array: [1 2 3]


In [237]:
# Size in bytes of an array
array_size_in_bytes=a.nbytes  # Size in bytes
print("Size of a in bytes:",array_size_in_bytes)

Size of a in bytes: 12


In [239]:
# Check if two arrays share memory
shared=np.shares_memory(a,copied_array)
print("Do a and copied_array share memory?",shared)

Do a and copied_array share memory? False


# Linear Algebra Functions

In [242]:
# create a matrix
matrix=np.array([[1,2],[3,4]])
matrix

array([[1, 2],
       [3, 4]])

In [244]:
import numpy as np

In [246]:
np.__version__

'1.26.4'

In [248]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

# creating Array

In [251]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [253]:
type(my_list)

list

In [255]:
arr=np.array(my_list)

In [257]:
arr

array([0, 1, 2, 3, 4, 5])

In [259]:
type(arr)

numpy.ndarray

In [261]:
type(arr)

numpy.ndarray

In [263]:
type(my_list)

list

In [265]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [267]:
np.arange(3.0)

array([0., 1., 2.])

In [269]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [271]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [273]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [275]:
np.arange(20,10) # 1st arg < 2nd arg

array([], dtype=int32)

In [277]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [279]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [281]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [283]:
np.arange(30,20) # 1st arg always be < then 2nd arg

array([], dtype=int32)

In [285]:
ar=np.arange(-30,20)

In [287]:
ar

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [289]:
np.arange(10,10)

array([], dtype=int32)

In [291]:
np.arange()

TypeError: arange() requires stop to be specified.

In [293]:
np.arange(10,30,5) # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [295]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [297]:
np.arange(10,30,5,)

array([10, 15, 20, 25])

In [299]:
np.zeros(3)

array([0., 0., 0.])

In [301]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [303]:
np.zeros((2,2),dtype=int)

array([[0, 0],
       [0, 0]])

In [305]:
zero=np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [307]:
zero=np.zeros([3,3])
print(zero)
print(type(zero))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [309]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [311]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [313]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [315]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [317]:
np.zeros((5,10)) # bydefault 1arg---will give row & 2nd arg-columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [319]:
n=(6,7)
n1=(6,8)
print(np.zeros(n1)) # parameter tunning

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [321]:
print(np.zeros(n,dtype=int)) # hyperparameter tunning

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [323]:
n

(6, 7)

In [325]:
n1

(6, 8)

In [327]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [329]:
np.ones(3)

array([1., 1., 1.])

In [331]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [333]:
n

(6, 7)

In [335]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [337]:
np.ones((5,4),dtype=int) # it will print by default 5 rows & 4 columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [339]:
np.twos((2,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [341]:
np.ones((6,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

# Range

In [344]:
range(5)

range(0, 5)

In [346]:
r=range(5)
r

range(0, 5)

In [348]:
for i in r:
    print(i)

0
1
2
3
4


In [350]:
list(range(5))

[0, 1, 2, 3, 4]

In [352]:
range(1,10)

range(1, 10)

In [354]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [356]:
list(range(1,10,3))

[1, 4, 7]

In [358]:
y=list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [360]:
np.random.rand(5)

array([0.4236548 , 0.64589411, 0.43758721, 0.891773  , 0.96366276])

In [362]:
np.random.randint(2,4)

2

In [364]:
np.random.randint(0,1)

0

In [366]:
np.random.randint(2,20) # 2nd argument is exclusive

3

In [368]:
np.random.randint(10,20,5)

array([16, 17, 17, 18, 11])

In [370]:
np.random.randint(1,6,4)

array([2, 1, 2, 5])

In [372]:
np.random.rand(3)

array([0.0202184 , 0.83261985, 0.77815675])

In [374]:
np.random.randint(30,20,10)

ValueError: low >= high

In [376]:
np.random.randint(-30,20,10)

array([ 17, -30, -12,   5,  -6,  19,  -1, -11, -11, -16])

In [378]:
np.random.randint(20,30,10)

array([27, 20, 21, 29, 29, 20, 24, 27, 23, 22])

In [380]:
np.random.randint(5,9)

8

In [382]:
np.random.randint(1,12,10)

array([3, 1, 1, 5, 6, 6, 7, 9, 5, 2])

In [384]:
np.random.randint(10,40,(10,10))

array([[25, 14, 19, 20, 36, 34, 11, 11, 17, 19],
       [35, 13, 16, 33, 21, 24, 28, 37, 10, 24],
       [13, 31, 22, 35, 20, 30, 21, 14, 16, 14],
       [25, 30, 13, 22, 14, 30, 18, 24, 25, 30],
       [13, 36, 33, 25, 23, 31, 31, 26, 27, 15],
       [19, 13, 10, 15, 10, 27, 28, 14, 12, 26],
       [39, 13, 12, 20, 23, 26, 17, 31, 19, 10],
       [20, 28, 21, 36, 33, 37, 12, 35, 12, 13],
       [37, 13, 28, 24, 13, 30, 27, 28, 37, 24],
       [19, 36, 11, 14, 20, 32, 21, 18, 21, 12]])

In [386]:
np.random.randint(1,100,(12,12))

array([[52, 81, 33, 55,  1, 39, 20, 47, 43, 57, 61, 78],
       [31, 25,  3,  4, 95, 99, 14, 41, 73, 20, 96, 73],
       [27, 67, 53, 68, 62, 15, 97,  5, 68, 12, 87, 78],
       [76, 57, 17, 25, 30, 22, 26, 81, 61, 62, 84, 34],
       [33, 71, 86, 32, 14, 72, 57, 25, 80, 42, 19, 41],
       [55, 80, 12, 39, 94,  2, 96, 45, 89, 25, 68, 83],
       [ 4, 77, 36, 87, 62, 70, 88, 44, 33, 12, 85, 11],
       [55, 38, 29,  3, 28, 84, 90, 24, 54, 52, 47, 21],
       [54, 30, 68, 36, 40, 10, 74, 42, 24,  4, 47, 91],
       [51,  4, 32, 10, 11, 28, 46, 72, 40, 62, 86, 98],
       [45, 35, 35, 89, 34,  6, 37,  1, 76, 35, 70, 54],
       [81, 63,  9, 62,  2, 82, 36, 92, 41, 37, 49, 26]])

In [388]:
np.arange(1,13).reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [390]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [392]:
b=np.random.randint(10,20,(5,4))
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [394]:
type(b)

numpy.ndarray

In [396]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [398]:
b[:]

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [400]:
b[1:3]

array([[11, 11, 12, 11],
       [14, 12, 15, 15]])

In [402]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [404]:
b[1,2]

12

In [406]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [408]:
b[1,3]

11

In [410]:
b[1,-1]

11

In [412]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [414]:
b[2:3]

array([[14, 12, 15, 15]])

In [416]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [418]:
b[0:-2]

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15]])

In [420]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [422]:
b[0,2]

13

In [424]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [426]:
b[0:2]

array([[13, 17, 13, 12],
       [11, 11, 12, 11]])

In [428]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [430]:
b[-5,-3]

17

In [432]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [434]:
b[-4,2]

12

In [436]:
np.random.randint(10,20,(4,4))

array([[17, 12, 13, 11],
       [19, 15, 19, 19],
       [12, 10, 19, 11],
       [19, 10, 16, 10]])

In [438]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [440]:
b[-4,-2]

12

In [442]:
b

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

In [444]:
b[-4:2]

array([[11, 11, 12, 11]])

In [446]:
b[:]

array([[13, 17, 13, 12],
       [11, 11, 12, 11],
       [14, 12, 15, 15],
       [15, 12, 15, 17],
       [17, 16, 11, 16]])

# Operations

In [449]:
a=np.random.randint(10,20,10)
a

array([14, 18, 14, 13, 13, 18, 18, 17, 10, 13])

In [451]:
id(a)

2445336582480

In [453]:
arr

array([0, 1, 2, 3, 4, 5])

In [455]:
arr2=np.random.randint(0,100,(10,10))

In [457]:
arr2

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [56, 23, 24,  4, 49, 87, 30, 54, 25, 20]])

In [459]:
arr

array([0, 1, 2, 3, 4, 5])

In [461]:
arr[:4]

array([0, 1, 2, 3])

In [463]:
arr2[:]

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [56, 23, 24,  4, 49, 87, 30, 54, 25, 20]])

In [465]:
arr2[0:5]

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53]])

In [467]:
arr2

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [56, 23, 24,  4, 49, 87, 30, 54, 25, 20]])

In [469]:
arr2[1,4]

14

In [471]:
arr2[0:]

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [56, 23, 24,  4, 49, 87, 30, 54, 25, 20]])

In [473]:
arr2[-5,5]

87

In [475]:
arr2

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [56, 23, 24,  4, 49, 87, 30, 54, 25, 20]])

In [477]:
arr2[-5,-5]

87

In [479]:
arr2

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [56, 23, 24,  4, 49, 87, 30, 54, 25, 20]])

In [481]:
arr2[-1,-2]

25

In [483]:
arr2

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [56, 23, 24,  4, 49, 87, 30, 54, 25, 20]])

In [485]:
arr2[::-1]

array([[56, 23, 24,  4, 49, 87, 30, 54, 25, 20],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [72, 71, 87, 13, 58, 81, 55, 64, 75, 92]])

In [487]:
arr2

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [56, 23, 24,  4, 49, 87, 30, 54, 25, 20]])

In [489]:
arr2[::-2]

array([[56, 23, 24,  4, 49, 87, 30, 54, 25, 20],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68]])

In [491]:
arr2

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [56, 23, 24,  4, 49, 87, 30, 54, 25, 20]])

In [493]:
arr2[::-3]

array([[56, 23, 24,  4, 49, 87, 30, 54, 25, 20],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [72, 71, 87, 13, 58, 81, 55, 64, 75, 92]])

In [495]:
arr2

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53],
       [58, 43, 55, 18, 45, 87, 65, 70, 53, 48],
       [94, 59, 80, 26, 35, 58, 49, 73, 44, 13],
       [70, 38, 39,  8, 13,  7, 80, 22, 79, 89],
       [ 8, 99,  6, 81, 71, 84, 89, 66, 60, 16],
       [56, 23, 24,  4, 49, 87, 30, 54, 25, 20]])

In [497]:
arr2[:-5]

array([[72, 71, 87, 13, 58, 81, 55, 64, 75, 92],
       [36, 25, 32, 42, 14, 86, 28, 20, 82, 68],
       [22, 99, 83,  7, 72, 61, 13,  5,  0,  8],
       [79, 79, 53, 11,  4, 39, 92, 45, 26, 74],
       [52, 49, 91, 51, 99, 18, 34, 51, 30, 53]])

In [499]:
arr

array([0, 1, 2, 3, 4, 5])

In [501]:
arr.max()

5

In [503]:
arr.min()

0

In [505]:
arr

array([0, 1, 2, 3, 4, 5])

In [507]:
arr.mean()

2.5

In [509]:
arr

array([0, 1, 2, 3, 4, 5])

In [511]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [513]:
from numpy import*
a=array([1,2,3,4,9])
median(a)

3.0

# Without work on import* Find the median,mode

In [516]:
arr

array([0, 1, 2, 3, 4, 5])

In [518]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [520]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [522]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [524]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [526]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [528]:
arr

array([0, 1, 2, 3, 4, 5])

In [530]:
arr.reshape(2,3,order='c')

array([[0, 1, 2],
       [3, 4, 5]])

In [532]:
arr.reshape(2,3,order='f')

array([[0, 2, 4],
       [1, 3, 5]])

In [534]:
arr

array([0, 1, 2, 3, 4, 5])

In [536]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [538]:
arr.reshape(1,4)

ValueError: cannot reshape array of size 6 into shape (1,4)

In [540]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [542]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [544]:
arr2.reshape(3,3)

ValueError: cannot reshape array of size 100 into shape (3,3)

# Indexing

In [547]:
mat=np.arange(0,100).reshape(10,10)

In [549]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [551]:
row=4
col=5

In [553]:
col

5

In [555]:
row

4

In [557]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [559]:
mat[row,col]

45

In [561]:
mat[4,5]

45

In [563]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [565]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [567]:
col=6

In [569]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [571]:
mat[6] # by default it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [573]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [575]:
# with Slices
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [577]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [579]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [581]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [583]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [585]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [587]:
mat[:col]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [589]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [591]:
row

4

In [593]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [595]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [597]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [599]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [601]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [603]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [605]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [607]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [609]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [611]:
row

4

In [613]:
col

6

In [615]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [617]:
mat[1,4]

14

In [619]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [621]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [623]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [625]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [627]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [629]:
mat[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [631]:
mat[6]

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [633]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [635]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [637]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [639]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [641]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [643]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [645]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [647]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [649]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [651]:
mat[0:10]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [653]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [655]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [657]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [659]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [661]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [663]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [665]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [667]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [669]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [671]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [673]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [675]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [677]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [679]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [681]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [683]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [689]:
mat[0,1]

1

In [691]:
mat[1,6]

16

In [694]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [696]:
mat[1,6]

16

In [698]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [700]:
mat[1:6]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [702]:
mat[1:]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [704]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [706]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [708]:
mat[0:1]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [710]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [712]:
mat[3,5]

35

In [714]:
mat[3:5]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [716]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [718]:
mat[1:2,2:4]

array([[12, 13]])

In [720]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [722]:
mat[2:3,2:3]

array([[22]])

In [724]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [726]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [728]:
mat[3:5,2:4]

array([[32, 33],
       [42, 43]])

In [730]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [732]:
mat[2:3,4:5]

array([[24]])

# Masking

In [735]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [737]:
id(mat)

2445336638256

In [739]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [741]:
mat[mat<50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [743]:
mat[mat<=50]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [745]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [747]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [749]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [751]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [753]:
a1=mat[mat<50]
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [755]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [757]:
a2=mat[mat>50]
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [759]:
a3=mat[mat>=50]
a3

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [761]:
a4=mat[mat==50]
a4

array([50])

# Python Program to generate to generat otp

In [778]:
import random
def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits='012345'
    otp=''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length=4 # you can change this to any lenth you preter
otp=generate_otp(otp_length)
print(f"your otp is:{otp}")

your otp is:4122


In [780]:
def wish():
    print('good even')
    wish()

def wish():
    print('good even')
    wish()

def wish():
    print('good even')
    wish()



In [782]:
def wish():
    print('good even')
    wish()
    wish()
    wish()

In [784]:
list1=['a','b','g',1,5]
print(list1.pop)

<built-in method pop of list object at 0x0000023959658200>


In [786]:
x=[1,2,3]
y=x.copy()
x.append(4)
print(x)

[1, 2, 3, 4]
